-- ProjNav VHDL simulation template: spi_interface_tf_v_tf.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
